<?php

/**
 * This is the model base class for the table "productos_clientes".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProductosClientes".
 *
 * Columns in table "productos_clientes" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $cliente_id
 * @property integer $producto_estrategico_id
 *
 */
abstract class BaseProductosClientes extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'productos_clientes';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Asociación entre producto y cliente|Asociación entre producto y cliente', $n);
	}

	public static function representingColumn() {
		return array(
			'cliente_id',
			'producto_estrategico_id',
		);
	}

	public function rules() {
		return array(
			array('cliente_id, producto_estrategico_id', 'required'),
			array('cliente_id, producto_estrategico_id', 'numerical', 'integerOnly'=>true),
			array('cliente_id, producto_estrategico_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'cliente_id' => null,
			'producto_estrategico_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('cliente_id', $this->cliente_id);
		$criteria->compare('producto_estrategico_id', $this->producto_estrategico_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
	
	public function buscarclientesporproducto($id_productoestrategico) {
		$criteria = new CDbCriteria;
	
		$criteria->compare('cliente_id', $this->cliente_id);
		$criteria->compare('producto_estrategico_id', $this->producto_estrategico_id);
		$criteria->select = 't.*';
		$criteria->condition='t.producto_estrategico_id='.$id_productoestrategico;
		
		$clientes = ProductosClientes::model()->findAll($criteria);
		
		return $clientes;

	}
	
	
	
}