<?php

/**
 * This is the model base class for the table "objetivos_objetivos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ObjetivosObjetivos".
 *
 * Columns in table "objetivos_objetivos" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $objetivo_estrategico_id
 * @property integer $objetivo_ministerial_id
 *
 */
abstract class BaseObjetivosObjetivos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'objetivos_objetivos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Asociación entre objetivos ministeriales y objetivos estrategicos|Asociación entre objetivos ministeriales y objetivos estrategicos', $n);
	}

	public static function representingColumn() {
		return array(
			'objetivo_estrategico_id',
			'objetivo_ministerial_id',
		);
	}

	public function rules() {
		return array(
			array('objetivo_estrategico_id, objetivo_ministerial_id', 'required'),
			array('objetivo_estrategico_id, objetivo_ministerial_id', 'numerical', 'integerOnly'=>true),
			array('objetivo_estrategico_id, objetivo_ministerial_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'objetivo_estrategico_id' => null,
			'objetivo_ministerial_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('objetivo_estrategico_id', $this->objetivo_estrategico_id);
		$criteria->compare('objetivo_ministerial_id', $this->objetivo_ministerial_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
	
	public function buscarObjetivosObjetivo($idobjetivoministerial) {
		$criteria = new CDbCriteria;
	
		$criteria->compare('objetivo_estrategico_id', $this->objetivo_estrategico_id);
		$criteria->compare('objetivo_ministerial_id', $this->objetivo_ministerial_id);
		$criteria->condition='objetivo_estrategico_id='.$idobjetivoministerial;
		$objetivosobjetivos = ObjetivosObjetivos::model()->findAll($criteria);
		
		return $objetivosobjetivos;
	}
	
}
