<?php

/**
 * This is the model base class for the table "indicadores_tipos_indicadores".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "IndicadoresTiposIndicadores".
 *
 * Columns in table "indicadores_tipos_indicadores" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $tipo_indicador_id
 * @property integer $indicador_id
 *
 */
abstract class BaseIndicadoresTiposIndicadores extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'indicadores_tipos_indicadores';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Indicadores Tipos Indicadores|Indicadores Tipos de Indicadores', $n);
	}

	public static function representingColumn() {
		return array(
			'tipo_indicador_id',
			'indicador_id',
		);
	}

	public function rules() {
		return array(
			array('tipo_indicador_id, indicador_id', 'required'),
			array('tipo_indicador_id, indicador_id', 'numerical', 'integerOnly'=>true),
			array('tipo_indicador_id, indicador_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'tipo_indicador_id' => null,
			'indicador_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('tipo_indicador_id', $this->tipo_indicador_id);
		$criteria->compare('indicador_id', $this->indicador_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}