<?php

/**
 * This is the model base class for the table "elementos_gestion_priorizados".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ElementosGestionPriorizados".
 *
 * Columns in table "elementos_gestion_priorizados" available as properties of the model,
 * followed by relations of table "elementos_gestion_priorizados" available as properties of the model.
 *
 * @property integer $id
 * @property integer $id_elemento_gestion
 * @property integer $id_planificacion
 * @property integer $estado
 *
 * @property ElementosGestion $idElementoGestion
 * @property Planificaciones $idPlanificacion
 */
abstract class BaseElementosGestionPriorizados extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'elementos_gestion_priorizados';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Elementos de Gestión Priorizados|Elementos de Gestión Priorizados', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('id_elemento_gestion, id_planificacion', 'required'),
			array('id_elemento_gestion, id_planificacion, estado', 'numerical', 'integerOnly'=>true),
			array('estado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, id_elemento_gestion, id_planificacion, estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idElementoGestion' => array(self::BELONGS_TO, 'ElementosGestion', 'id_elemento_gestion'),
			'idPlanificacion' => array(self::BELONGS_TO, 'Planificaciones', 'id_planificacion'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'id_elemento_gestion' => null,
			'id_planificacion' => null,
			'estado' => Yii::t('app', 'Estado'),
			'idElementoGestion' => null,
			'idPlanificacion' => null,
		);
	}

	public function search() {
		
		$criteria = new CDbCriteria;
		$criteria->compare('id', $this->id);
		$criteria->compare('id_elemento_gestion', $this->id_elemento_gestion);
		$criteria->compare('id_planificacion', $this->id_planificacion);
		$criteria->compare('estado', $this->estado);
		
		//$criteria->condition='t.estado = 1 ';
		/*$criteria->join=' 
		INNER JOIN elementos_gestion elemen ON t.id_elemento_gestion = elemen.id
		INNER JOIN subcriterios sub ON elemen.id_subcriterio = sub.id
		INNER JOIN criterios cri ON sub.id_criterio = cri.id
		';*/
			
		
		if(isset(Yii::app()->session['idPeriodo'])){
            $criteria->join=' 
            	INNER JOIN planificaciones plan on t.id_planificacion = plan.id
                INNER JOIN periodos_procesos pp on plan.periodo_proceso_id = pp.id';
            $criteria->distinct =true;
            $criteria->select='t.*';
            $criteria->condition='t.estado = 1  AND pp.id = '.Yii::app()->session['idPeriodo'];
        }else{
            $criteria->condition='t.id=0';
        }
		
//print_r ($criteria);
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}