<?php

/**
 * This is the model base class for the table "centros_costos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CentrosCostos".
 *
 * Columns in table "centros_costos" available as properties of the model,
 * followed by relations of table "centros_costos" available as properties of the model.
 *
 * @property integer $id
 * @property integer $division_id
 * @property string $nombre
 * @property string $descripcion
 * @property integer $estado
 *
 * @property Divisiones $division
 * @property Personas[] $personases
 * @property Subproductos[] $subproductoses
 */
abstract class BaseCentrosCostos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'centros_costos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Centro De Costo|Centros De Costos', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre, descripcion, division_id', 'required'),
			array('division_id, estado', 'numerical', 'integerOnly'=>true),
			array('nombre', 'length', 'max'=>200),
			array('division_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, division_id, nombre, descripcion, estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'division' => array(self::BELONGS_TO, 'Divisiones', 'division_id'),
			'ejecucionPresupuestarias' => array(self::HAS_MANY, 'EjecucionPresupuestaria', 'id_centro_costo'),
			//'subproductoses' => array(self::HAS_MANY, 'Subproductos', 'centro_costo_id'),
			'elementosGestionResponsables' => array(self::HAS_MANY, 'ElementosGestionResponsable', 'centro_costo_id'),
			'users' => array(self::MANY_MANY, 'User', 'users_centros(centro_id, user_id)'),
			'productosEstrategicoses' => array(self::MANY_MANY, 'ProductosEstrategicos', 'producto_estrategico_centro_costo(centro_costo_id, producto_estrategico_id)'),
            'itemesPresupuestarioses' => array(self::MANY_MANY, 'ItemesPresupuestarios', 'productos_itemes(centro_costo_id, item_presupuestario_id)','condition' => 'itemesPresupuestarioses.estado = 1'),
		    'productosItemes' => array(self::HAS_MANY, 'ProductosItemes', 'centro_costo_id'),
            'lineasAccions' => array(self::HAS_MANY, 'LineasAccion', 'centro_costo_id'),
        );
	}

	public function pivotModels() {
		return array(
		  'users' => 'UsersCentros',
		  'productosEstrategicoses' => 'ProductoEstrategicoCentroCosto',
            'itemesPresupuestarioses' => 'ProductosItemes',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'division_id' => null,
			'nombre' => Yii::t('app', 'Nombre'),
			'descripcion' => Yii::t('app', 'Descripción'),
			'estado' => Yii::t('app', 'Estado'),
			'division' => null,
			'productosEstrategicoses' => null,
            'itemesPresupuestarioses' => null,
			//'personases' => null,
			'subproductoses' => null,
			'users' => 'Usuarios',
			'User' => 'Usuario',
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('division_id', $this->division_id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('estado', 1);
		//$criteria->condition='t.estado = 1';

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
    
         
}