<?php

/**
 * This is the model base class for the table "la_actores".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LaActores".
 *
 * Columns in table "la_actores" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_usuario
 * @property integer $id_la
 *
 */
abstract class BaseLaActores extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'la_actores';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Asociación LA y usuarios|Asociación LA y usuarios', $n);
	}

	public static function representingColumn() {
		return array(
			'id_usuario',
			'id_la',
		);
	}

	public function rules() {
		return array(
			array('id_usuario, id_la', 'required'),
			array('id_usuario, id_la', 'numerical', 'integerOnly'=>true),
			array('id_usuario, id_la', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_usuario' => null,
			'id_la' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_usuario', $this->id_usuario);
		$criteria->compare('id_la', $this->id_la);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}