<?php

/**
 * This is the model base class for the table "menu_principal".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MenuPrincipal".
 *
 * Columns in table "menu_principal" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $parent_id
 * @property integer $nivel
 * @property string $descripcion
 * @property integer $estado
 * @property string $controller
 *
 */
abstract class BaseMenuPrincipal extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'menu_principal';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Menu Principal|Menu Principal', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('parent_id, nivel, estado', 'numerical', 'integerOnly'=>true),
			array('nombre, descripcion, controller', 'length', 'max'=>255),
			array('nombre, parent_id, nivel, descripcion, estado, controller', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, nombre, parent_id, nivel, descripcion, estado, controller', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		  'parent' => array(self::BELONGS_TO, 'MenuPrincipal', 'parent_id'), //the column in 'parent' containing 'this' id
          'children' => array(self::HAS_MANY, 'MenuPrincipal', 'parent_id'), //the column in 'this' containing the child id
          
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nombre' => Yii::t('app', 'Nombre'),
			'parent_id' => Yii::t('app', 'Parent'),
			'nivel' => Yii::t('app', 'Nivel'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'estado' => Yii::t('app', 'Estado'),
			'controller' => Yii::t('app', 'Controller'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('parent_id', $this->parent_id);
		$criteria->compare('nivel', $this->nivel);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('estado', $this->estado);
		$criteria->compare('controller', $this->controller, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}