<?php

/**
 * This is the model base class for the table "evaluacion_jornada".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EvaluacionJornada".
 *
 * Columns in table "evaluacion_jornada" available as properties of the model,
 * followed by relations of table "evaluacion_jornada" available as properties of the model.
 *
 * @property integer $id
 * @property string $descripcion
 * @property string $fecha_jornada
 * @property integer $estado
 * @property integer $planificacion_id
 *
 * @property Planificaciones $planificacion
 * @property EvaluacionJornadaDocumentos[] $evaluacionJornadaDocumentoses
 */
abstract class BaseEvaluacionJornada extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'evaluacion_jornada';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EvaluacionJornada|EvaluacionJornadas', $n);
	}

	public static function representingColumn() {
		return 'descripcion';
	}

	public function rules() {
		return array(
			array('estado, planificacion_id', 'numerical', 'integerOnly'=>true),
			array('descripcion, fecha_jornada', 'safe'),
			array('descripcion, fecha_jornada, estado, planificacion_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, descripcion, fecha_jornada, estado, planificacion_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'planificacion' => array(self::BELONGS_TO, 'Planificaciones', 'planificacion_id'),
			'evaluacionJornadaDocumentoses' => array(self::HAS_MANY, 'EvaluacionJornadaDocumentos', 'evaluacion_jornada_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'descripcion' => 'Comentarios de la Jornada de Evaluación',
			'fecha_jornada' => 'Fecha de Jornada',
			'estado' => Yii::t('app', 'Estado'),
			'planificacion_id' => null,
			'planificacion' => null,
			'evaluacionJornadaDocumentoses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('fecha_jornada', $this->fecha_jornada, true);
		$criteria->compare('estado', $this->estado);
		$criteria->compare('planificacion_id', $this->planificacion_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}