<?php

/**
 * This is the model base class for the table "viaticos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Viaticos".
 *
 * Columns in table "viaticos" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property double $monto_100
 * @property integer $estado
 * @property integer $grado_desde
 * @property integer $grado_hasta
 *
 */
abstract class BaseViaticos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'viaticos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Viático|Viáticos', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('monto_100, grado_desde, grado_hasta', 'required'),
			array('id, estado, grado_desde, grado_hasta, monto_100', 'numerical', 'integerOnly'=>true),
			array('monto_100', 'numerical'),
			array('id, grado_desde, grado_hasta', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, monto_100, estado, grado_desde, grado_hasta', 'safe', 'on'=>'search'),
			array('grado_desde','validacionhasta'),
		);
	}
	
	public function validacionhasta($atributte, $params){
		if($this->grado_desde >= $this->grado_hasta){
			$this->addError('grado_desde','Grado Desde debe ser menor que Grado Hasta');
		}
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'monto_100' => Yii::t('app', 'Monto'),
			'estado' => Yii::t('app', 'Estado'),
			'grado_desde' => Yii::t('app', 'Grado De'),
			'grado_hasta' => Yii::t('app', 'Hasta'),
		);
	}

	public function search(){
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('monto_100', $this->monto_100);
		$criteria->compare('estado', $this->estado);
		$criteria->compare('grado_desde', $this->grado_desde);
		$criteria->compare('grado_hasta', $this->grado_hasta);
		$criteria->condition='t.estado = 1';

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}