<?php

/**
 * This is the model base class for the table "itemes_presupuestarios".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ItemesPresupuestarios".
 *
 * Columns in table "itemes_presupuestarios" available as properties of the model,
 * followed by relations of table "itemes_presupuestarios" available as properties of the model.
 *
 * @property integer $id
 * @property integer $tipo_item_id
 * @property string $nombre
 * @property integer $estado
 *
 * @property Actividades[] $actividades
 * @property TiposItemes $tipoItem
 * @property ProductosEstrategicos[] $productosEstrategicoses
 */
abstract class BaseItemesPresupuestarios extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'itemes_presupuestarios';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Ítem Presupuestario|Ítems Presupuestarios', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre, tipo_item_id', 'required'),
			array('tipo_item_id, estado', 'numerical', 'integerOnly'=>true),
			array('nombre', 'length', 'max'=>200),
			array('tipo_item_id,estado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, tipo_item_id, nombre, estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'actividades' => array(self::MANY_MANY, 'Actividades', 'itemes_actividades(item_presupuestario_id, actividad_id)'),
			'tipoItem' => array(self::BELONGS_TO, 'TiposItemes', 'tipo_item_id'),
			//'productosEstrategicoses' => array(self::MANY_MANY, 'ProductosEstrategicos', 'productos_itemes(item_presupuestario_id, producto_estrategico_id)'),
		    'productosItemes' =>array(self::HAS_MANY, 'ProductosItemes', 'item_presupuestario_id'),
        );
	}

	public function pivotModels() {
		return array(
			'actividades' => 'ItemesActividades',
			'productosEstrategicoses' => 'ProductosItemes',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'tipo_item_id' => null,
			'nombre' => Yii::t('app', 'Nombre'),
			'estado' => Yii::t('app', 'Estado'),
			'actividades' => null,
			'tipoItem' => null,
			'productosEstrategicoses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('tipo_item_id', $this->tipo_item_id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('estado', $this->estado);
		$criteria->condition='t.estado = 1';

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}