<?php

/**
 * This is the model base class for the table "desafio_desafio".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DesafioDesafio".
 *
 * Columns in table "desafio_desafio" available as properties of the model,
 * followed by relations of table "desafio_desafio" available as properties of the model.
 *
 * @property integer $desafio_estrategico_id
 * @property integer $desafio_estrategico_mm_id
 *
 * @property DesafiosEstrategicos $desafioEstrategicoMm
 * @property DesafiosEstrategicos $desafioEstrategico
 */
abstract class BaseDesafioDesafio extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'desafio_desafio';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Asociación de Desafios Estratégicos|Asociación de Desafios Estratégicos', $n);
	}

	public static function representingColumn() {
		return array(
			'desafio_estrategico_id',
			'desafio_estrategico_mm_id',
		);
	}

	public function rules() {
		return array(
			array('desafio_estrategico_id, desafio_estrategico_mm_id', 'required'),
			array('desafio_estrategico_id, desafio_estrategico_mm_id', 'numerical', 'integerOnly'=>true),
			array('desafio_estrategico_id, desafio_estrategico_mm_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'desafioEstrategicoMm' => array(self::BELONGS_TO, 'DesafiosEstrategicos', 'desafio_estrategico_mm_id'),
			'desafioEstrategico' => array(self::BELONGS_TO, 'DesafiosEstrategicos', 'desafio_estrategico_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'desafio_estrategico_id' => null,
			'desafio_estrategico_mm_id' => null,
			'desafioEstrategicoMm' => null,
			'desafioEstrategico' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('desafio_estrategico_id', $this->desafio_estrategico_id);
		$criteria->compare('desafio_estrategico_mm_id', $this->desafio_estrategico_mm_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}