<?php

/**
 * This is the model base class for the table "hitos_actividades".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "HitosActividades".
 *
 * Columns in table "hitos_actividades" available as properties of the model,
 * followed by relations of table "hitos_actividades" available as properties of the model.
 *
 * @property integer $id
 * @property integer $id_actividad
 * @property integer $avance_actual
 * @property integer $estado
 * @property string $actividad_mes
 *
 * @property Actividades $idActividad
 */
abstract class BaseHitosActividades extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'hitos_actividades';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'HitosActividades|HitosActividades', $n);
	}

	public static function representingColumn() {
		return 'actividad_mes';
	}

	public function rules() {
		return array(
			array('id_actividad, actividad_mes', 'required'),
			array('id_actividad, avance_actual, estado', 'numerical', 'integerOnly'=>true),
			array('actividad_mes', 'length', 'max'=>12),
			array('estado,avance_actual', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, id_actividad, avance_actual, estado, actividad_mes', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idActividad' => array(self::BELONGS_TO, 'Actividades', 'id_actividad'),
			'hitosActividades' => array(self::HAS_MANY, 'HitosActividades', 'id_actividad'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'id_actividad' => null,
			'avance_actual' => Yii::t('app', 'Avance Actual'),
			'estado' => Yii::t('app', 'Estado'),
			'actividad_mes' => Yii::t('app', 'Actividad Mes'),
			'idActividad' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('id_actividad', $this->id_actividad);
		$criteria->compare('avance_actual', $this->avance_actual);
		$criteria->compare('estado', 1);
		$criteria->compare('actividad_mes', $this->actividad_mes, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
	
	
}