<?php

/**
 * This is the model base class for the table "desafios_objetivos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DesafiosObjetivos".
 *
 * Columns in table "desafios_objetivos" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $desafio_estrategico_id
 * @property integer $objetivo_estrategico_id
 *
 */
abstract class BaseDesafiosObjetivos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'desafios_objetivos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Asociación intermedia entre desafios y objetivos|Asociación intermedia entre desafios y objetivos', $n);
	}

	public static function representingColumn() {
		return array(
			'desafio_estrategico_id',
			'objetivo_estrategico_id',
		);
	}

	public function rules() {
		return array(
			array('desafio_estrategico_id, objetivo_estrategico_id', 'required'),
			array('desafio_estrategico_id, objetivo_estrategico_id', 'numerical', 'integerOnly'=>true),
			array('desafio_estrategico_id, objetivo_estrategico_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'desafio_estrategico_id' => null,
			'objetivo_estrategico_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('desafio_estrategico_id', $this->desafio_estrategico_id);
		$criteria->compare('objetivo_estrategico_id', $this->objetivo_estrategico_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}