<?php

/**
 * This is the model base class for the table "producto_estrategico_centro_costo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProductoEstrategicoCentroCosto".
 *
 * Columns in table "producto_estrategico_centro_costo" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $producto_estrategico_id
 * @property integer $centro_costo_id
 * @property integer $porcentaje
 * @property integer $monto
 *
 */
abstract class BaseProductoEstrategicoCentroCosto extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'producto_estrategico_centro_costo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Producto Estrategico por Centro de Costo|Producto Estrategico por Centro de Costos', $n);
	}

	public static function representingColumn() {
		return array(
			'producto_estrategico_id',
			'centro_costo_id',
		);
	}

	public function rules() {
		return array(
			array('producto_estrategico_id, centro_costo_id, porcentaje', 'numerical', 'integerOnly'=>true),
			array('producto_estrategico_id, centro_costo_id, porcentaje', 'default', 'setOnEmpty' => true, 'value' => null),
			array('producto_estrategico_id, centro_costo_id, porcentaje', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'producto_estrategico_id' => null,
			'centro_costo_id' => null,
			'porcentaje' => Yii::t('app', 'Porcentaje'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('producto_estrategico_id', $this->producto_estrategico_id);
		$criteria->compare('centro_costo_id', $this->centro_costo_id);
		$criteria->compare('porcentaje', $this->porcentaje);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
	
	public function buscarporcporpestrategico($producto_estrategico_id) {
		$criteria = new CDbCriteria;
	
		$criteria->compare('producto_estrategico_id', $this->producto_estrategico_id);
		$criteria->compare('centro_costo_id', $this->centro_costo_id);
		$criteria->compare('porcentaje', $this->porcentaje);
		$criteria->condition='t.producto_estrategico_id='.$producto_estrategico_id;
	
		$porcentaje = ProductoEstrategicoCentroCosto::model()->findAll($criteria);
		
		return $porcentaje;
	}
    
   
}