<?php

/**
 * This is the model base class for the table "divisiones".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Divisiones".
 *
 * Columns in table "divisiones" available as properties of the model,
 * followed by relations of table "divisiones" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 * @property integer $estado
 *
 * @property CentrosCostos[] $centrosCostoses
 * @property ProductosEstrategicos[] $productosEstrategicoses
 */
abstract class BaseDivisiones extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'divisiones';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Centro de Responsabilidad|Centros de Responsabilidad', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre, descripcion', 'required'),
			array('estado', 'numerical', 'integerOnly'=>true),
			array('nombre', 'length', 'max'=>200),
			array('id, nombre, descripcion, estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'centrosCostoses' => array(self::HAS_MANY, 'CentrosCostos', 'division_id'),
			'productosEstrategicoses' => array(self::HAS_MANY, 'ProductosEstrategicos', 'division_id'),
			'ejecucionPresupuestarias' => array(self::HAS_MANY, 'EjecucionPresupuestaria', 'id_division'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nombre' => Yii::t('app', 'Nombre'),
			'descripcion' => Yii::t('app', 'Descripción'),
			'estado' => Yii::t('app', 'Estado'),
			'centrosCostoses' => null,
			'productosEstrategicoses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('estado', $this->estado);
		$criteria->condition='t.estado = 1';

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
	
	
}