<?php

/**
 * This is the model base class for the table "perspectivas_estrategicas".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PerspectivasEstrategicas".
 *
 * Columns in table "perspectivas_estrategicas" available as properties of the model,
 * followed by relations of table "perspectivas_estrategicas" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $estado
 *
 * @property DesafiosEstrategicos[] $desafiosEstrategicoses
 * @property ObjetivosEstrategicos[] $objetivosEstrategicoses
 */
abstract class BasePerspectivasEstrategicas extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'perspectivas_estrategicas';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Perspectiva Estratégica del BSC|Perspectivas Estratégicas del BSC', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre', 'required'),
			array('estado', 'numerical', 'integerOnly'=>true),
			array('nombre', 'length', 'max'=>200),
			array('id, nombre, estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'desafiosEstrategicoses' => array(self::HAS_MANY, 'DesafiosEstrategicos', 'perspectiva_estrategica_id'),
			'objetivosEstrategicoses' => array(self::HAS_MANY, 'ObjetivosEstrategicos', 'perspectiva_estrategica_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nombre' => Yii::t('app', 'Nombre'),
			'estado' => Yii::t('app', 'Estado'),
			'desafiosEstrategicoses' => null,
			'objetivosEstrategicoses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('estado', $this->estado);
		$criteria->condition='t.estado = 1';

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}