<?php

/**
 * This is the model base class for the table "leyes_mandatos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LeyesMandatos".
 *
 * Columns in table "leyes_mandatos" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 * @property string $url
 * @property integer $estado
 *
 */
abstract class BaseLeyesMandatos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'leyes_mandatos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Ley y Mandato|Leyes y Mandatos', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre, descripcion, url', 'required'),
			array('id, estado', 'numerical', 'integerOnly'=>true),
			array('nombre', 'length', 'max'=>200),
			array('url', 'length', 'max'=>300),
			array('url', 'url'),
			array('id, nombre, descripcion, url, estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nombre' => Yii::t('app', 'Nombre'),
			'descripcion' => Yii::t('app', 'Descripción'),
			'url' => Yii::t('app', 'Url'),
			'estado' => Yii::t('app', 'Estado'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('estado', $this->estado);
		$criteria->condition='t.estado = 1';

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
	
	
	public function buscarLeyesMandatos() {
		$criteria = new CDbCriteria;
	
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('estado', $this->estado);
		$criteria->condition='t.estado = 1';

		$leyesmandatos=LeyesMandatos::model()->findAll($criteria);
		
		return $leyesmandatos;
	
	}
}