<?php

/**
 * This is the model base class for the table "la_elem_gestion_documentos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LaElemGestionDocumentos".
 *
 * Columns in table "la_elem_gestion_documentos" available as properties of the model,
 * followed by relations of table "la_elem_gestion_documentos" available as properties of the model.
 *
 * @property integer $id
 * @property integer $la_elem_id
 * @property string $nombre
 * @property integer $estado
 * @property LaElemGestion $laElem
 */
abstract class BaseLaElemGestionDocumentos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'la_elem_gestion_documentos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'LaElemGestionDocumentos|LaElemGestionDocumentoses', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('la_elem_id, nombre', 'required'),
			array('la_elem_id, estado', 'numerical', 'integerOnly'=>true),
			array('nombre', 'length', 'max'=>200),
			array('id, la_elem_id, nombre, estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'laElem' => array(self::BELONGS_TO, 'LaElemGestion', 'la_elem_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'la_elem_id' => null,
			'nombre' => Yii::t('app', 'Nombre'),
			'laElem' => null,
			'estado' => Yii::t('app', 'Estado'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('la_elem_id', $this->la_elem_id);
		$criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('estado', 1);
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}