<?php

/**
 * This is the model base class for the table "tipos_la".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TiposLa".
 *
 * Columns in table "tipos_la" available as properties of the model,
 * followed by relations of table "tipos_la" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $estado
 *
 * @property LineasAccion[] $lineasAccions
 */
abstract class BaseTiposLa extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tipos_la';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Tipos Lineas de acción|Tipos de lineas de acción', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre, estado', 'required'),
			array('estado', 'numerical', 'integerOnly'=>true),
			array('nombre', 'length', 'max'=>300),
			array('id, nombre, estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'lineasAccions' => array(self::HAS_MANY, 'LineasAccion', 'id_tipo_la'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nombre' => Yii::t('app', 'Nombre'),
			'estado' => Yii::t('app', 'Estado'),
			'lineasAccions' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('estado', $this->estado);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}