<?php

/**
 * This is the model base class for the table "cierres_internos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CierresInternos".
 *
 * Columns in table "cierres_internos" available as properties of the model,
 * followed by relations of table "cierres_internos" available as properties of the model.
 *
 * @property integer $id
 * @property integer $id_etapa
 * @property string $observaciones
 * @property string $archivo
 * @property string $fecha_cierre
 * @property integer $id_usuario
 * @property integer $id_planificacion
 * @property integer $estado
 *
 * @property Etapas $idEtapa
 * @property Users $idUsuario
 * @property Planificaciones $idPlanificacion
 */
abstract class BaseCierresInternos extends GxActiveRecord {

	public $documento;
		
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cierres_internos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Cierres Internos|Cierres Internos', $n);
	}

	public static function representingColumn() {
		return 'observaciones';
	}

	public function rules() {
		return array(
			array('documento', 'file', 'types'=>'pdf'),
			array('observaciones', 'required'),
			array('id_etapa, id_usuario, id_planificacion, estado,cierre_etapa', 'numerical', 'integerOnly'=>true),
			array('archivo,formulario_h,formulario_a1', 'length', 'max'=>200),
			array('estado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, id_etapa, observaciones, archivo, fecha_cierre, id_usuario, id_planificacion, estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idEtapa' => array(self::BELONGS_TO, 'Etapas', 'id_etapa'),
			'idUsuario' => array(self::BELONGS_TO, 'Users', 'id_usuario'),
			'idPlanificacion' => array(self::BELONGS_TO, 'Planificaciones', 'id_planificacion'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'id_etapa' => null,
			'observaciones' => Yii::t('app', 'Observaciones'),
			'archivo' => Yii::t('app', 'Archivo'),
			'formulario_h'=> Yii::t('app', 'Formulario H'),
			'formulario_a1'=> Yii::t('app', 'Formulario A.1'),
			'fecha_cierre' => Yii::t('app', 'Fecha Cierre'),
			'id_usuario' => null,
			'id_planificacion' => null,
			'estado' => Yii::t('app', 'Estado'),
			'cierre_etapa'=> null,
			'idEtapa' => null,
			'idUsuario' => null,
			'idPlanificacion' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('id_etapa', $this->id_etapa);
		$criteria->compare('observaciones', $this->observaciones, true);
		$criteria->compare('archivo', $this->archivo, true);
		$criteria->compare('formulario_h', $this->formulario_h, true);
		$criteria->compare('formulario_a1', $this->formulario_a1, true);
		$criteria->compare('fecha_cierre', $this->fecha_cierre, true);
		$criteria->compare('id_usuario', $this->id_usuario);
		$criteria->compare('id_planificacion', $this->id_planificacion);
		$criteria->compare('estado', $this->estado);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}