<?php

/**
 * This is the model base class for the table "users_centros".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UsersCentros".
 *
 * Columns in table "users_centros" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $user_id
 * @property integer $centro_id
 *
 */
abstract class BaseUsersCentros extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'users_centros';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Asociación entre usuarios y centros|Asociación entre usuarios y centros', $n);
	}

	public static function representingColumn() {
		return array(
			'user_id',
			'centro_id',
		);
	}

	public function rules() {
		return array(
			array('user_id, centro_id', 'numerical', 'integerOnly'=>true),
			array('user_id, centro_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('user_id, centro_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'user_id' => null,
			'centro_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('centro_id', $this->centro_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}