<?php

/**
 * This is the model base class for the table "objetivos_ministeriales".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ObjetivosMinisteriales".
 *
 * Columns in table "objetivos_ministeriales" available as properties of the model,
 * followed by relations of table "objetivos_ministeriales" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 * @property integer $estado
 *
 * @property ObjetivosEstrategicos[] $objetivosEstrategicoses
 */
abstract class BaseObjetivosMinisteriales extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'objetivos_ministeriales';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Objetivo Ministerial|Objetivos Ministeriales', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre, descripcion', 'required'),
			array('estado', 'numerical', 'integerOnly'=>true),
			array('nombre', 'length', 'max'=>200),
			array('id, nombre, descripcion, estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'objetivosEstrategicoses' => array(self::MANY_MANY, 'ObjetivosEstrategicos', 'objetivos_objetivos(objetivo_ministerial_id, objetivo_estrategico_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'objetivosEstrategicoses' => 'ObjetivosObjetivos',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nombre' => Yii::t('app', 'Nombre'),
			'descripcion' => Yii::t('app', 'Descripción'),
			'estado' => Yii::t('app', 'Estado'),
			'objetivosEstrategicoses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('estado', $this->estado);
 		if(isset(Yii::app()->session['idPeriodo'])){
			$criteria->join='
 					INNER JOIN objetivos_objetivos oo ON t.id = oo.objetivo_ministerial_id
 					INNER JOIN objetivos_estrategicos oe ON oo.objetivo_estrategico_id = oe.id
 					INNER JOIN desafios_objetivos do ON oe.id = do.objetivo_estrategico_id
             		INNER JOIN desafios_estrategicos de ON do.desafio_estrategico_id = de.id
             		INNER JOIN planificaciones pl ON de.planificacion_id = pl.id
             		INNER JOIN periodos_procesos pp ON pl.periodo_proceso_id = pp.id';
 			$criteria->distinct =true;
 			$criteria->select='t.*';
 			$criteria->condition='pp.id = '.Yii::app()->session['idPeriodo'].' AND t.estado = 1  AND oe.estado = 1';
 		}else{
 			$criteria->condition='t.id =0';
 		}
		//$criteria->condition='t.estado = 1';
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
	
	public function buscarObjetivosMinisteriales() {
		$criteria = new CDbCriteria;
		
		$criteria->compare('id', $this->id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('estado', $this->estado);
		if(isset(Yii::app()->session['idPeriodo'])){
			$criteria->join='
					INNER JOIN objetivos_objetivos oo ON t.id = oo.objetivo_ministerial_id
					INNER JOIN objetivos_estrategicos oe ON oo.objetivo_estrategico_id = oe.id					
					INNER JOIN desafios_objetivos do ON oo.objetivo_estrategico_id = do.objetivo_estrategico_id
            		INNER JOIN desafios_estrategicos de ON do.desafio_estrategico_id = de.id
            		INNER JOIN planificaciones pl ON de.planificacion_id = pl.id
            		INNER JOIN periodos_procesos pp ON pl.periodo_proceso_id = pp.id';
			$criteria->distinct =true;
			$criteria->select='t.*';
			$criteria->condition='pp.id = '.Yii::app()->session['idPeriodo'].' AND t.estado = 1 AND oe.estado = 1';
		}else{
			$criteria->condition='t.id =0';
		}
	
		$objetivosministeriales=ObjetivosMinisteriales::model()->findAll($criteria);
		
		return $objetivosministeriales;
	}
}