<?php

/**
 * This is the model base class for the table "evaluacion_jornada_documentos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EvaluacionJornadaDocumentos".
 *
 * Columns in table "evaluacion_jornada_documentos" available as properties of the model,
 * followed by relations of table "evaluacion_jornada_documentos" available as properties of the model.
 *
 * @property integer $id
 * @property string $archivo
 * @property string $fecha_creacion
 * @property integer $evaluacion_jornada_id
 * @property integer $estado
 *
 * @property EvaluacionJornada $evaluacionJornada
 */
abstract class BaseEvaluacionJornadaDocumentos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'evaluacion_jornada_documentos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EvaluacionJornadaDocumentos|EvaluacionJornadaDocumentoses', $n);
	}

	public static function representingColumn() {
		return 'archivo';
	}

	public function rules() {
		return array(
			array('evaluacion_jornada_id', 'required'),
			array('evaluacion_jornada_id, estado', 'numerical', 'integerOnly'=>true),
			array('archivo', 'length', 'max'=>300),
			array('fecha_creacion', 'safe'),
			array('archivo, fecha_creacion, estado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, archivo, fecha_creacion, evaluacion_jornada_id, estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'evaluacionJornada' => array(self::BELONGS_TO, 'EvaluacionJornada', 'evaluacion_jornada_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'archivo' => Yii::t('app', 'Archivo'),
			'fecha_creacion' => Yii::t('app', 'Fecha Creacion'),
			'evaluacion_jornada_id' => null,
			'estado' => Yii::t('app', 'Estado'),
			'evaluacionJornada' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('archivo', $this->archivo, true);
		$criteria->compare('fecha_creacion', $this->fecha_creacion, true);
		$criteria->compare('evaluacion_jornada_id', $this->evaluacion_jornada_id);
		$criteria->compare('estado', $this->estado);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}